
# ===========================================================================
#  BACKEND: devenv.sh  (https://devenv.sh/ad-hoc-developer-environments/)
# ---------------------------------------------------------------------------
#  Spliced in by the renderer for a `?devenv` request, in place of
#  _backend-nix.sh. Same contract (nix_ensure + cooee_backend_* hooks), but
#  packages are provisioned through a single devenv.sh environment: devenv is
#  installed on top of Nix, each nixpkgs attr a module would `nix profile
#  install` is written into a generated devenv.nix, devenv builds the
#  environment, and its profile bin dir is prepended to PATH — so the tool
#  resolves immediately afterwards exactly as the nix-profile backend's does.
#
#  We write a real (minimal) devenv.nix rather than the newer ad-hoc
#  `--option packages:pkgs` flag: it works on any devenv version and sidesteps
#  the empty-directory edge cases ad-hoc invocations hit on a fresh project.
# ===========================================================================
COOEE_DEVENV_DIR="${COOEE_DEVENV_DIR:-$HOME/.config/coo-ee/devenv}"
_COOEE_DEVENV_PKGS=()   # nixpkgs attrs accumulated across nix_ensure calls

# Hook: install devenv on top of Nix and seed the project (called by module_base
# once Nix is on PATH).
cooee_backend_setup() { cooee_devenv_install; }

# Hook: which JDK majors to install. A single devenv profile is one buildEnv and
# can't hold two JDKs at once — their files (lib/modules, …) collide, and the
# per-install --priority the nix backend uses to break that tie isn't available.
# Install just the first (lowest) requested major, and say so.
cooee_backend_jdks() {
  if (( $# > 1 )); then
    warn "java: devenv backend provisions a single JDK; using $1 (requested: $*)."
  fi
  printf '%s\n' "${1:-}"
}

# Provision <flakeref> by adding its nixpkgs attr to the devenv environment.
# Same signature as the nix backend's nix_ensure; extra nix-profile flags
# (e.g. --priority) don't apply to devenv and are ignored.
nix_ensure() {  # nix_ensure <match> <flakeref> [extra nix flags...]
  local match=$1; shift
  local pkg=${1#nixpkgs#}   # nixpkgs#nodejs_22 -> nodejs_22
  local p
  for p in "${_COOEE_DEVENV_PKGS[@]}"; do
    [[ "$p" == "$pkg" ]] && { ok "already present (devenv): $match"; return 0; }
  done
  _COOEE_DEVENV_PKGS+=("$pkg")
  cooee_devenv_sync || return 1
  ok "installed (devenv): $match"
}

# Install devenv itself (idempotent) into the default Nix profile, then seed the
# project dir. Uses `nix profile install` directly (NOT nix_ensure, which routes
# back through devenv here and would recurse).
cooee_devenv_install() {
  if command -v devenv >/dev/null 2>&1; then
    ok "devenv already installed: $(devenv version 2>/dev/null || echo present)"
  else
    # Prefer the prebuilt nixpkgs#devenv from the binary cache (fast, no Rust
    # source build); --accept-flake-config lets devenv's own cache be used too.
    log "Installing devenv.sh via Nix (prebuilt nixpkgs#devenv)..."
    nix profile install nixpkgs#devenv --accept-flake-config \
      || die "failed to install devenv (nixpkgs#devenv)."
    command -v devenv >/dev/null 2>&1 || die "devenv not on PATH after install."
    ok "devenv ready: $(devenv version 2>/dev/null || echo installed)"
  fi
  cooee_devenv_seed_project
}

# Seed a minimal, valid devenv project in COOEE_DEVENV_DIR: a devenv.yaml that
# pins the nixpkgs input (the same nixpkgs-unstable channel the nix backend
# draws from) and a git repo (devenv reads git-tracked files and is happiest
# inside a repo). Best-effort and idempotent; the package list lands in
# devenv.nix, (re)generated per sync by cooee_devenv_write_config.
cooee_devenv_seed_project() {
  mkdir -p "$COOEE_DEVENV_DIR"
  if [[ ! -f "$COOEE_DEVENV_DIR/devenv.yaml" ]]; then
    cat > "$COOEE_DEVENV_DIR/devenv.yaml" <<'YAML'
# Generated by coo.ee/env for the ?devenv backend — do not hand-edit.
inputs:
  nixpkgs:
    url: github:NixOS/nixpkgs/nixpkgs-unstable
YAML
  fi
  [[ -f "$COOEE_DEVENV_DIR/devenv.nix" ]] || cooee_devenv_write_config
  if command -v git >/dev/null 2>&1 && [[ ! -d "$COOEE_DEVENV_DIR/.git" ]]; then
    ( cd "$COOEE_DEVENV_DIR" \
        && git init -q \
        && git -c user.name=coo.ee -c user.email=coo@ee.invalid \
             -c commit.gpgsign=false add -A \
        && git -c user.name=coo.ee -c user.email=coo@ee.invalid \
             -c commit.gpgsign=false commit -qm "coo.ee devenv seed" ) >/dev/null 2>&1 || true
  fi
}

# (Re)generate devenv.nix from the accumulated package list. nixpkgs attrs map
# straight to pkgs.<attr> (nodejs_22 -> pkgs.nodejs_22, temurin-bin-21 -> ...).
cooee_devenv_write_config() {
  local p body=""
  for p in "${_COOEE_DEVENV_PKGS[@]}"; do body+="    pkgs.${p}"$'\n'; done
  cat > "$COOEE_DEVENV_DIR/devenv.nix" <<NIX
# Generated by coo.ee/env for the ?devenv backend — do not hand-edit.
{ pkgs, ... }:
{
  packages = [
${body}  ];
}
NIX
}

# Build the environment from the current package list and prepend its profile
# bin dir to PATH (now + persisted, mirroring base.sh's handling of the nix
# profile). devenv maintains a stable $dir/.devenv/profile symlink that
# re-points on each rebuild, so persisting it keeps a future shell's PATH valid
# as packages accrue; DEVENV_PROFILE (the underlying store path) is the fallback.
cooee_devenv_sync() {
  (( ${#_COOEE_DEVENV_PKGS[@]} )) || return 0
  cooee_devenv_write_config
  local dir="$COOEE_DEVENV_DIR"
  log "devenv: building environment (packages: ${_COOEE_DEVENV_PKGS[*]})..."
  ( cd "$dir" && devenv shell bash -- -c 'true' ) \
    || die "devenv: failed to build environment for: ${_COOEE_DEVENV_PKGS[*]}"

  local bin=""
  if [[ -d "$dir/.devenv/profile/bin" ]]; then
    bin="$dir/.devenv/profile/bin"
  else
    local profile
    profile=$( cd "$dir" && devenv shell bash -- -c 'printf %s "${DEVENV_PROFILE:-}"' 2>/dev/null ) || true
    [[ -n "$profile" && -d "$profile/bin" ]] && bin="$profile/bin"
  fi
  [[ -n "$bin" ]] || die "devenv: could not locate the built profile bin dir under $dir."

  # Prepend once — the bin path (a stable symlink) doesn't change between syncs.
  case ":$PATH:" in
    *":$bin:"*) : ;;
    *)
      export PATH="$bin:$PATH"
      echo "export PATH=\"$bin:\$PATH\"" >> "$COOEE_PROFILE"
      printf 'PATH=%s\n' "$PATH" >> "$COOEE_HARNESS_ENV"
      cooee_forward_to_harness "PATH=$PATH"
      ;;
  esac
}
